-- local ReplicatedStorage = game:GetService("ReplicatedStorage")
-- local ServerScriptService = game:GetService("ServerScriptService")

-- local MainRequirer = require(ReplicatedStorage.Shared.MainRequirer)

-- MainRequirer.loadModules(ServerScriptService.Server.Services)
-- MainRequirer.loadModules(ReplicatedStorage.Shared.Systems)

-- -- a little delay to make sure all modules are moved before we start loading them
-- task.delay(0.2, MainRequirer.moveValidModulesToServerScriptService)
